version: "3"
services:
  movies:
    environment:
      - OMDB_KEY=faf7e5bb
    build:
      context: ./movies
      dockerfile: Dockerfile
    restart: always
    container_name: movies
    ports:
      - 8081:8081

  api-gateway:
    environment:
      - MOVIE_GRPC_ADDRESS=movies:8081
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: always
    container_name: api-gateway
    ports:
      - 8080:8080
  
