// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	movies "github.com/ranggakusuma/go-kit-example/api-gateway/movies"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SearchMovies provides a mock function with given fields: ctx, request
func (_m *Service) SearchMovies(ctx context.Context, request movies.SearchMovieRequest) (movies.SearchMovieResponse, error) {
	ret := _m.Called(ctx, request)

	var r0 movies.SearchMovieResponse
	if rf, ok := ret.Get(0).(func(context.Context, movies.SearchMovieRequest) movies.SearchMovieResponse); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Get(0).(movies.SearchMovieResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, movies.SearchMovieRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
